version: "3.2"
services:
  db:
    image: postgres
    container_name: suva_postgresdb
    restart: always
    
    volumes:
       - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: suvadip
      POSTGRES_PASSWORD: suvadip
      POSTGRES_DB: tododb

